apiVersion: apps/v1
kind: Deployment
metadata:
  name: spale
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: spale
  template:
    metadata:
      labels:
        app: spale
    spec:
      containers:
        - name: spale
          image: ghcr.io/magnm/spale:v1
          imagePullPolicy: Always
          resources:
            requests:
              memory: 32Mi
              cpu: 5m
          ports:
            - containerPort: 8080
            - containerPort: 8443
          env:
            - name: NAMESPACE_SELECTOR
              value: "*"
            - name: LOG_LEVEL
              value: debug
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
      serviceAccountName: spale
